name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Flutter pub get (root)
        run: flutter pub get

      - name: Run tests (root)
        run: flutter test -r expanded

      - name: Flutter pub get (example)
        working-directory: example
        run: flutter pub get

      - name: Run tests (example)
        working-directory: example
        run: flutter test -r expanded

      - name: Enforce TDD: require tests when lib/ changes
        if: github.event_name == 'pull_request'
        run: |
          set -euo pipefail
          BASE_SHA=$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")
          HEAD_SHA=$(jq -r '.pull_request.head.sha' "$GITHUB_EVENT_PATH")
          CHANGED=$(git diff --name-only "$BASE_SHA".."$HEAD_SHA")
          if echo "$CHANGED" | grep -E '^(lib/|example/lib/)' >/dev/null; then
            if ! echo "$CHANGED" | grep -E '^test/|^example/test/' >/dev/null; then
              echo 'Changes in lib/ or example/lib/ detected, but no test files changed (test/ or example/test/).'
              echo 'Please add or update tests to comply with TDD policy.'
              exit 1
            fi
          fi


